apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rsync-backup
  namespace: rsync
  labels:
    app: rsync-backup
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: rsync-password
  namespace: rsync
type: Opaque
stringData:
  password: "123456"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsync-server
  namespace: rsync
  labels:
    app: rsync
    tier: server
spec:
  selector:
    matchLabels:
      app: rsync
      tier: server
  template:
    metadata:
      name: rsync-server
      labels:
        app: rsync
        tier: server
    spec:
      containers:
      - name: rsync-server
        image: dyadin/rsync-server
        imagePullPolicy: IfNotPresent
        ports:
        - name: rsync
          containerPort: 873
        env:
        - name: username
          value: "backupuser"
        - name: backup_path
          value: "/backup/"
        - name: password
          valueFrom:
            secretKeyRef:
              name: rsync-password
              key: password
        volumeMounts:
        - mountPath: /backup
          name: rsync-backup
        livenessProbe:
          tcpSocket:
            port: 873
          initialDelaySeconds: 5
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 873
          initialDelaySeconds: 5
          timeoutSeconds: 5
      volumes:
      - name: rsync-backup
        persistentVolumeClaim:
          claimName: rsync-backup
---
apiVersion: v1
kind: Service
metadata:
  name: rsync-server-svc
  namespace: rsync
  labels:
    tier: rsync
    app: server
spec:
  ports:
    - name: rsync
      port: 873
      protocol: TCP
      targetPort: 873
  selector:
    app: rsync
    tier: server
  