#application/wordpress/wordpress-deployment.yaml 

apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  namespace: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30080
  selector:
    app: wordpress
    tier: frontend
  type: NodePort

---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: wordpress-nginx
  namespace: wordpress
  labels:
    app: wordpress
    tier: frontend
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: dyadin/windows-wordpress-nginx:latest
        imagePullPolicy: IfNotPresent
        name: wordpress-nginx
        env:
        - name: DBHOST
          value: wordpress-mysql-svc
        - name: PHPHOST
          value: wordpress-php-svc
        - name: DBPASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 80
          name: wordpress-nginx
        stdin: true
        tty: true
